name: ci

on: [push, pull_request]

jobs:
  Ñi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node_modules
      run: yarn install
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
